[package]
name = "mae_burn"
version = "0.1.1"
edition = "2024"
license = "MIT"
description = "Masked Autoencoder using Burn framework"

[dependencies]
burn = { version = "0.21.0", default-features = false, features = ["autodiff"] }
rand = "0.8"

[dev-dependencies]
burn = { version = "0.21.0", default-features = false, features = ["wgpu"] }
